<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>158ca1a7-a268-4c38-a73e-763f047abe3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSearchOutgoing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSearchOutgoing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aab815bd-4a31-4ba3-a56d-e3029030dc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9aaef223-06d5-45ec-a961-75ec8bd8d91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mr-2</value>
      <webElementGuid>3e5b19c6-2d95-435a-86c0-5c292ca7e0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>FilterOutgoingDashboard(false)</value>
      <webElementGuid>7d56a175-539b-4116-af03-e5105dc1ef33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSearchOutgoing</value>
      <webElementGuid>51fa99ea-977e-4596-bab9-e5829318c37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSearchOutgoing</value>
      <webElementGuid>8d81e6ad-bc1d-4e3a-8f9d-5dbd2281b462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        
                                        Search
                                    </value>
      <webElementGuid>b2ab9bde-3b2e-4bfd-a920-3df788302ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSearchOutgoing&quot;)</value>
      <webElementGuid>0c440341-4b91-46cf-abf5-ce46e6c70562</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSearchOutgoing']</value>
      <webElementGuid>a21220a5-1b31-4aa7-8863-3500cdf6713d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterPopUp']/div/div/div[2]/div[3]/div/div/div/button</value>
      <webElementGuid>f88eae03-a71f-4f86-8e71-f1b0beb57772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End'])[1]/following::button[2]</value>
      <webElementGuid>2149ecc0-4005-47b3-8290-c72e89973b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start'])[1]/following::button[3]</value>
      <webElementGuid>6213b3cd-0b12-43d8-975d-e444c468f740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DASHBOARD'])[1]/preceding::button[2]</value>
      <webElementGuid>059a25fb-9348-44cb-9c9c-d1274f6cc9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>9601e7f4-15cd-4006-8532-74c28f9bfbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>0923368f-4cb6-4e21-b0f8-9a5d2666f8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnSearchOutgoing' and @name = 'btnSearchOutgoing' and (text() = '
                                        
                                        Search
                                    ' or . = '
                                        
                                        Search
                                    ')]</value>
      <webElementGuid>20071d1e-884b-48e6-89e4-54fd8ef3f308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
