<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_End_k-input-button k-button k-icon-b_7d5a2d</name>
   <tag></tag>
   <elementGuidId>11235ae1-7fe8-480a-8d1a-efd038d1ef45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-datepicker.k-input.form-control.k-input-solid.k-input-md.k-rounded-md.k-hover > button.k-input-button.k-button.k-icon-button.k-button-md.k-button-solid.k-button-solid-base</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d745b8cd-e454-4d03-bbe7-aa97697e0b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>193938c8-7474-4ee2-893a-0320bb871300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0e696fec-5048-4f56-91d4-a6b446f2074e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-button k-button k-icon-button k-button-md k-button-solid k-button-solid-base</value>
      <webElementGuid>de456bfd-fa07-4cde-8b83-fc259df93189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0c11a13-c8c3-4a4e-9c81-7b14c567e63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07cc7726-27f0-438e-b432-be4c6903918a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterPopUp&quot;)/div[@class=&quot;col-md-12 grid-margin&quot;]/div[@class=&quot;card card-popup-filter&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-xs-10 col-sm-10 col-md-10 col-lg-10&quot;]/span[@class=&quot;k-datepicker k-input form-control k-input-solid k-input-md k-rounded-md k-hover&quot;]/button[@class=&quot;k-input-button k-button k-icon-button k-button-md k-button-solid k-button-solid-base&quot;]</value>
      <webElementGuid>dc88ba50-2123-457d-be7e-de52b3b9712b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>2d25306c-449c-4454-875b-0e5e9355e628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterPopUp']/div/div/div[2]/div[2]/div/div[2]/div/span/button</value>
      <webElementGuid>bd2ae585-5416-42e8-82d8-bfb16bc343ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End'])[1]/following::button[1]</value>
      <webElementGuid>37be1aca-a79f-40fa-b62d-b2825d1b2ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start'])[1]/following::button[2]</value>
      <webElementGuid>3afc4df9-75e5-4788-b39c-53d1853bfd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/button</value>
      <webElementGuid>3b7b347b-a460-46a7-a9f0-ce26751a5f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>60d45ad0-a517-44cd-8bf2-fcd9f9c86d40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
