<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start_dpDateFromOutgoing</name>
   <tag></tag>
   <elementGuidId>e9dc51bc-9db7-4ca1-aa58-acb713389e5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dpDateFromOutgoing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dpDateFromOutgoing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e642f8c-cc71-4091-bd45-87fc703e0e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control k-input-inner</value>
      <webElementGuid>a88ce2f1-38ef-4419-93ec-1467a3ba1239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dpDateFromOutgoing</value>
      <webElementGuid>a74fdfd1-d885-4251-9ac2-852271a526eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dpDateFromOutgoing</value>
      <webElementGuid>cbb8692f-5b99-4893-89c7-66ee56baaea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>436cd80c-c21e-4ccd-84f0-031bdc9158ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6fe6faa-622e-4deb-828e-6ffbe483ee68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>3db04edf-4f4b-4461-a30a-cf8be4ac5f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>8dc9bbd8-1ec5-4203-839f-426f8f4c130d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de1b49dc-892a-413d-9011-125d6c05176b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>grid</value>
      <webElementGuid>c6b02e9b-3f37-46d3-9248-69eab054af3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dpDateFromOutgoing_dateview</value>
      <webElementGuid>19131b63-ab84-4c59-a2eb-18e7b4bca79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>053eb64c-17e9-4015-9733-d2a045a51681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc8e437b-00c4-4c7f-b4f7-81a22b3b33c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>67494f5e-c153-4301-829e-9b54418a2121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dpDateFromOutgoing&quot;)</value>
      <webElementGuid>bd2d13fc-f37e-4eee-a696-a0e49eddc394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dpDateFromOutgoing']</value>
      <webElementGuid>77accd4a-a7e4-4a19-bf0a-503834e8dbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterPopUp']/div/div/div[2]/div[2]/div/div/div/span/input</value>
      <webElementGuid>a74f867b-edd4-4207-8f4f-03c43d9d696f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>d00e5be2-00bc-4774-8c41-28c15e2a2650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dpDateFromOutgoing' and @name = 'dpDateFromOutgoing' and @title = 'datepicker' and @type = 'text']</value>
      <webElementGuid>eee5ad55-69d8-4dfc-8322-76eff52a5356</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
