<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End_dpDateToOutgoing</name>
   <tag></tag>
   <elementGuidId>7a126833-ebe8-45d0-a85d-3d592b910a90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dpDateToOutgoing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dpDateToOutgoing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f89a60e9-88a9-4ccf-a8ab-59991c8c8d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control k-input-inner</value>
      <webElementGuid>660ec579-cd11-4cb4-ba75-a44e189f4151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dpDateToOutgoing</value>
      <webElementGuid>d2bf4b03-d30d-4d79-afbe-99ebf10bef18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dpDateToOutgoing</value>
      <webElementGuid>437c0781-50f3-4d9f-8949-1bfb3fd9d114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>deea431d-78b5-4bd5-8f1b-f4aefe5313bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b0c928f-1cea-4978-9bd3-b36c0ec72d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>78dace39-b3f4-4dff-9cbf-502b4e9f4bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>4a3aaa4f-fc61-4129-b0a6-f323552c9a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d87ef6e2-bdb2-4f30-8f8a-3568fd8a686d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>grid</value>
      <webElementGuid>1244a7e3-b90a-4e29-bc0f-ccba822c39a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dpDateToOutgoing_dateview</value>
      <webElementGuid>69ccf651-b868-4fcf-ba95-aa078f8c26fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fdc55125-a795-442d-a214-be52bd75c3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7f687bcc-501f-4d26-a3bd-1f96a5f58495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5cebe3b4-d5b1-44ea-b69c-b19c05904b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dpDateToOutgoing&quot;)</value>
      <webElementGuid>70a8865f-437d-42b6-88f3-707ea51220a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dpDateToOutgoing']</value>
      <webElementGuid>e85b1dbb-2940-48fb-8205-4851c361c4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterPopUp']/div/div/div[2]/div[2]/div/div[2]/div/span/input</value>
      <webElementGuid>21cf4eaf-f196-4c22-9cf0-bf1fd0c6114b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>c92a46ca-1858-434b-9ba6-92be849eb5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dpDateToOutgoing' and @name = 'dpDateToOutgoing' and @title = 'datepicker' and @type = 'text']</value>
      <webElementGuid>e38a1417-2302-40b0-88ab-64e6fcea84a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
