<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_29</name>
   <tag></tag>
   <elementGuidId>0bfd7fd6-39ed-4964-85fd-7a464046d81a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.k-calendar-td.k-hover > span.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='d15fdc1a-3f89-4c75-be91-86fef4d082d8']/div[2]/table/tbody/tr[5]/td[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>87394f31-7828-483b-bf91-408e5e699e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>140e7e06-00fe-44cc-ac0e-d94b887d5fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link </value>
      <webElementGuid>9c33391c-391c-4e56-aef2-891386d7422d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a28e2cb8-cdbd-4d15-9309-818ef0cc9331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2024/10/29</value>
      <webElementGuid>4f49b70d-ed81-47f1-bbf5-0dc21e3dcf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Friday, November 29, 2024</value>
      <webElementGuid>512375db-743c-4fdb-886f-75c31aae5907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>939c1666-ebe1-4193-8eed-94c73cf06355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d15fdc1a-3f89-4c75-be91-86fef4d082d8&quot;)/div[@class=&quot;k-calendar-view k-align-items-start k-justify-content-center k-hstack k-calendar-monthview&quot;]/table[@class=&quot;k-calendar-table&quot;]/tbody[@class=&quot;k-calendar-tbody&quot;]/tr[@class=&quot;k-calendar-tr&quot;]/td[@class=&quot;k-calendar-td k-hover&quot;]/span[@class=&quot;k-link&quot;]</value>
      <webElementGuid>66c7c0c1-e277-4dfa-84f3-ef3870800343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d15fdc1a-3f89-4c75-be91-86fef4d082d8']/div[2]/table/tbody/tr[5]/td[6]/span</value>
      <webElementGuid>78781371-6886-42a3-9462-48a58dff058b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[34]</value>
      <webElementGuid>6d760de8-a0e1-4912-963c-79032c17074d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[34]</value>
      <webElementGuid>8e10b79f-12b6-4e65-804e-69938c7dc278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday, November 28, 2024'])[1]/preceding::span[9]</value>
      <webElementGuid>231da13b-fc43-437d-b2cc-3400326134a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]/span</value>
      <webElementGuid>77b5c231-9c0b-4471-8bef-ff6b888a0483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Friday, November 29, 2024' and (text() = '29' or . = '29')]</value>
      <webElementGuid>26de34ce-e7f3-4a4f-8eaa-62b042ea013b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
