<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Outgoing</name>
   <tag></tag>
   <elementGuidId>2f4ee413-681e-4038-8974-99d38a6733ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tabstrip-tab-1']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>264c60b8-0777-4dc5-8879-6efd0817c514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>2dc3258d-1656-4655-a972-bffc16278baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2e1f95ca-961b-4b54-a916-94deb7aa1090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outgoing</value>
      <webElementGuid>74f56966-2576-4cef-8997-ec1b6eadb86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabstrip-tab-1&quot;)/span[@class=&quot;k-link&quot;]</value>
      <webElementGuid>b8e47e99-e118-4688-a9ae-5251f4b7c1b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tabstrip-tab-1']/span[2]</value>
      <webElementGuid>4e3beb0b-591c-4b59-b094-54016efa51a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DASHBOARD'])[1]/following::span[2]</value>
      <webElementGuid>df629b09-8773-44d4-8f9e-d31a2117d4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::span[2]</value>
      <webElementGuid>55be0334-a0c2-4844-8190-3716db2fd715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoming'])[2]/preceding::span[2]</value>
      <webElementGuid>1df874dc-4a6c-4fad-a215-9c2d209e109b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anzo'])[1]/preceding::span[4]</value>
      <webElementGuid>a1b7a19b-cda8-435a-87b3-832842c4c52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span[2]</value>
      <webElementGuid>a464f313-646c-4063-8f2c-0b2cf9f56b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Outgoing' or . = 'Outgoing')]</value>
      <webElementGuid>391c7bfd-dfd2-41c0-ae72-96b2da7c4e83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
