<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_December 2024</name>
   <tag></tag>
   <elementGuidId>244c2099-bf81-49f1-9c10-c7382d7b13dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='c94ac121-c81b-4444-9e97-3ffec6e360aa']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fdd22130-7f3f-4fbe-ada9-30f7f2c5731f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button-text</value>
      <webElementGuid>65ba2236-bc17-4db5-b7e2-c3dd4c1bc34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>December 2024</value>
      <webElementGuid>31be0120-7125-4012-bd63-7ef1292d427d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c94ac121-c81b-4444-9e97-3ffec6e360aa&quot;)/span[@class=&quot;k-button-text&quot;]</value>
      <webElementGuid>fe49e3de-047b-4b14-9ea2-6031e27d0686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='c94ac121-c81b-4444-9e97-3ffec6e360aa']/span</value>
      <webElementGuid>8cc9bae4-7fc4-4e1f-a493-af0140ccbfc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data available'])[3]/following::span[4]</value>
      <webElementGuid>829ea5a1-0b61-4d47-b429-105e63ff22a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Percentage Process Transaction'])[3]/following::span[4]</value>
      <webElementGuid>98a1cd13-3867-4806-82d9-7c9db22d6767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/preceding::span[3]</value>
      <webElementGuid>425d05ad-5781-4f91-92ac-8b2171a4bb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[1]/preceding::span[3]</value>
      <webElementGuid>78e97ccf-99f2-42be-9b31-34ecc9ed8cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='December 2024']/parent::*</value>
      <webElementGuid>6723df04-aa99-4e0d-9d53-876e909285d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>33a27f67-f511-4d80-b153-1bbfd87c8b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'December 2024' or . = 'December 2024')]</value>
      <webElementGuid>b8056332-1a6e-4173-a8a4-fab68d8c4a3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
