<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1_1</name>
   <tag></tag>
   <elementGuidId>feee9a19-039b-4184-b1d5-db10f2511ef5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='d9cce581-b9ce-4755-bcf4-2e2b679c2b38']/div[2]/table/tbody/tr/td[6]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.k-calendar-td.k-hover > span.k-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21bba104-276f-406d-a3ea-fc58a113dd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2431dd94-a158-4987-aaee-f301896965e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link </value>
      <webElementGuid>06c3c256-0108-4622-b293-49225f6635aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cd4c990a-801b-494d-a3dd-5bf3764fa41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2024/2/1</value>
      <webElementGuid>be3dd47d-79dd-49c0-bba1-bef7b289d099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Friday, March 01, 2024</value>
      <webElementGuid>af7a4ee8-dc52-493b-905f-1e1927ad55d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a5c31bd4-6dc2-4904-8f6b-5b6be5abc851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d9cce581-b9ce-4755-bcf4-2e2b679c2b38&quot;)/div[@class=&quot;k-calendar-view k-align-items-start k-justify-content-center k-hstack k-calendar-monthview&quot;]/table[@class=&quot;k-calendar-table&quot;]/tbody[@class=&quot;k-calendar-tbody&quot;]/tr[@class=&quot;k-calendar-tr&quot;]/td[@class=&quot;k-calendar-td k-hover&quot;]/span[@class=&quot;k-link&quot;]</value>
      <webElementGuid>a09ae136-4697-40de-8cb9-4a0f0b1840f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d9cce581-b9ce-4755-bcf4-2e2b679c2b38']/div[2]/table/tbody/tr/td[6]/span</value>
      <webElementGuid>9508d31b-b075-458d-abaa-1452666921bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[6]</value>
      <webElementGuid>1a7d2bb1-7dd7-4f6d-9544-e4d79ff55d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[6]</value>
      <webElementGuid>1922a217-69d4-4f4e-b3af-4720001809ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wednesday, November 20, 2024'])[1]/preceding::span[37]</value>
      <webElementGuid>a2d8219b-1881-469f-b0d0-aa1bdb788d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>c576c372-8c4f-4c60-bbb1-04815229abcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/span</value>
      <webElementGuid>6c2d8b93-8f7d-4a90-93e8-cc8db4530ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Friday, March 01, 2024' and (text() = '1' or . = '1')]</value>
      <webElementGuid>91ef6918-1f66-413c-b37f-32df5050c95c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
