<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>bde36516-1af8-42ea-880a-6f832bdb4729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.k-calendar-td.k-hover > span.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='d5c3a2b5-05f1-4bff-98b0-c47c552fdb73']/div[2]/table/tbody/tr/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0648d7c4-9334-400d-ae44-93c52fac01f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2cea04c1-912c-40d0-9a31-5f4167becbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link </value>
      <webElementGuid>0ec9e9f4-492a-4a5b-9d0f-ea6a15b8a30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8347bd5e-5c40-44e5-999a-66ab090f22aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2024/0/1</value>
      <webElementGuid>5849e59f-6a23-4a4a-a9a5-d0f7cb39896b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Monday, January 01, 2024</value>
      <webElementGuid>aa66504f-9cd2-421c-bf6d-7ff735dcc7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bbe4c8b4-2cae-4f7e-a2e2-35e3afb8f092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d5c3a2b5-05f1-4bff-98b0-c47c552fdb73&quot;)/div[@class=&quot;k-calendar-view k-align-items-start k-justify-content-center k-hstack k-calendar-monthview&quot;]/table[@class=&quot;k-calendar-table&quot;]/tbody[@class=&quot;k-calendar-tbody&quot;]/tr[@class=&quot;k-calendar-tr&quot;]/td[@class=&quot;k-calendar-td k-hover&quot;]/span[@class=&quot;k-link&quot;]</value>
      <webElementGuid>6cf49505-2f80-41dc-b851-137e44d89a56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d5c3a2b5-05f1-4bff-98b0-c47c552fdb73']/div[2]/table/tbody/tr/td[2]/span</value>
      <webElementGuid>170cb083-3629-4eae-85cc-531c71968329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[2]</value>
      <webElementGuid>6271057d-232d-4e82-b65b-6af9de61e94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[2]</value>
      <webElementGuid>8b7f5782-a4bc-4eae-b915-03c08de8ee7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday, December 19, 2024'])[1]/preceding::span[41]</value>
      <webElementGuid>ef371752-3bb8-4139-bdd6-8238d3b1255e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>0cccd351-f648-448f-a102-5dd3c5e26413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>c75b3c1f-100d-4705-bdad-61a950c3e5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Monday, January 01, 2024' and (text() = '1' or . = '1')]</value>
      <webElementGuid>b56fc7ac-bfb9-435b-a9ca-dfe35664552d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dba639f8-6780-4a7f-973d-cf4cbecc25fd']/div[2]/table/tbody/tr/td[2]/span</value>
      <webElementGuid>ebeedb21-a45b-4763-906f-b0af4617c10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wednesday, November 20, 2024'])[1]/preceding::span[41]</value>
      <webElementGuid>e033fd44-4ac4-4843-81dd-96f19eedc3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Monday, July 01, 2024' and (text() = '1' or . = '1')]</value>
      <webElementGuid>410a22ca-2ccf-4b45-85a3-76f03092bb0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
