<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_No data available_k-calendar-nav-prev _4e0900</name>
   <tag></tag>
   <elementGuidId>e35cf021-06fa-4879-9e5c-a4a7623d24eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='d9cce581-b9ce-4755-bcf4-2e2b679c2b38']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-calendar-nav-prev.k-button.k-button-md.k-rounded-md.k-button-flat.k-button-flat-base.k-icon-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8c5dfd2b-8c49-4319-96a9-251a5b81db6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e02c17e5-3aae-4903-a9d3-1eebe37dc437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>be377f7b-23d3-453d-abef-63b4c16fd59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>prev</value>
      <webElementGuid>db15e49f-4372-4863-a169-c1ed9888e31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53605db4-11c6-4465-b547-fa8b7ecf7108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-calendar-nav-prev k-button k-button-md k-rounded-md k-button-flat k-button-flat-base k-icon-button</value>
      <webElementGuid>74f23fa8-acc6-4b02-804d-67ee54bc02c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>3d5561d0-9a52-489e-9733-98d2d13a40fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8250cf09-68fb-4541-b5a2-bdc2fb313814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d9cce581-b9ce-4755-bcf4-2e2b679c2b38&quot;)/div[@class=&quot;k-header k-hstack&quot;]/span[@class=&quot;k-calendar-nav-prev k-button k-button-md k-rounded-md k-button-flat k-button-flat-base k-icon-button&quot;]</value>
      <webElementGuid>bb8209c7-0a38-4fb4-a936-0a0aad637903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d9cce581-b9ce-4755-bcf4-2e2b679c2b38']/div/span</value>
      <webElementGuid>10273f14-cb87-4809-ba11-4317329e22ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data available'])[3]/following::span[1]</value>
      <webElementGuid>63b6600c-104c-43c4-be4e-c274f18a3fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject New:'])[1]/following::span[1]</value>
      <webElementGuid>7b4d34fa-2d35-4508-8c5c-d983fc5b7952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='November 2024'])[1]/preceding::span[2]</value>
      <webElementGuid>6cd61e3e-b380-4397-b3de-b35f4b688229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/preceding::span[6]</value>
      <webElementGuid>c3239681-ef24-4008-a49c-1c01f030f8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/span</value>
      <webElementGuid>ad6101fc-9390-417b-a383-f45b5fed1f0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
