<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_30</name>
   <tag></tag>
   <elementGuidId>5bfc8515-85f0-4d70-957f-8200843e0c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.k-calendar-td.k-weekend.k-hover > span.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c1d3b630-e3be-4bd8-9c85-36dcbc0be199']/div[2]/table/tbody/tr[5]/td[7]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c479c75-8ff9-4ad1-80f0-1913ed166abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6de1bd98-f17d-4dbb-97ad-58236d45a75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link </value>
      <webElementGuid>61825163-8d2e-4cd6-ad9e-25b44a8de183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3efaafea-01d0-4048-afc7-095e8a1b20d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2024/10/30</value>
      <webElementGuid>8ff35281-3ca1-4445-87c3-46841944ed90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Saturday, November 30, 2024</value>
      <webElementGuid>f562603c-5536-424a-8727-577f22664331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>a5b52d32-e343-4674-bd42-4065778ef6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c1d3b630-e3be-4bd8-9c85-36dcbc0be199&quot;)/div[@class=&quot;k-calendar-view k-align-items-start k-justify-content-center k-hstack k-calendar-monthview&quot;]/table[@class=&quot;k-calendar-table&quot;]/tbody[@class=&quot;k-calendar-tbody&quot;]/tr[@class=&quot;k-calendar-tr&quot;]/td[@class=&quot;k-calendar-td k-weekend k-hover&quot;]/span[@class=&quot;k-link&quot;]</value>
      <webElementGuid>61788d46-4b15-4712-8355-41ca9bd253d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c1d3b630-e3be-4bd8-9c85-36dcbc0be199']/div[2]/table/tbody/tr[5]/td[7]/span</value>
      <webElementGuid>1244d46e-e39d-4b33-a819-e8dc02b1c4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::span[35]</value>
      <webElementGuid>76123e29-6fdc-4ad3-8d0b-edcdbbaca2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[2]/following::span[35]</value>
      <webElementGuid>e3dd4f52-53ba-4918-9014-3f2b6c63f6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday, November 28, 2024'])[2]/preceding::span[8]</value>
      <webElementGuid>920c5a73-c522-431f-80e5-b99243ebb954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/table/tbody/tr[5]/td[7]/span</value>
      <webElementGuid>1ce3d573-7473-4a7b-862d-6de0eb6dd29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Saturday, November 30, 2024' and (text() = '30' or . = '30')]</value>
      <webElementGuid>1e7c364b-5870-412a-839a-fbd11b0ff73f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
