<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jan</name>
   <tag></tag>
   <elementGuidId>e6e999e3-3dde-42f9-8418-989592890610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.k-calendar-td.k-hover > span.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='d5c3a2b5-05f1-4bff-98b0-c47c552fdb73']/div[2]/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>860cd4c6-02a2-4917-9729-54ab4075592c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ceecc70d-cf54-4ed5-9470-a32d098b556b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>d12db6b0-ab22-4c37-9e46-75e364669e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>193b0f2c-cae1-447c-9030-e996159e14a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2024/0/1</value>
      <webElementGuid>bffe558e-771e-40c4-9fec-1b977cc26cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>January</value>
      <webElementGuid>07e90c52-04d5-4267-a5a8-8ff292455086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jan</value>
      <webElementGuid>26e1eec4-be9c-4058-98be-f2d34afa38d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d5c3a2b5-05f1-4bff-98b0-c47c552fdb73&quot;)/div[@class=&quot;k-calendar-view k-align-items-start k-justify-content-center k-hstack k-calendar-yearview&quot;]/table[@class=&quot;k-calendar-table&quot;]/tbody[@class=&quot;k-calendar-tbody&quot;]/tr[@class=&quot;k-calendar-tr&quot;]/td[@class=&quot;k-calendar-td k-hover&quot;]/span[@class=&quot;k-link&quot;]</value>
      <webElementGuid>2e4631d4-9d84-4310-9cda-ceaa7d3f6f38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d5c3a2b5-05f1-4bff-98b0-c47c552fdb73']/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>8e9b8d3f-81bd-410a-8c09-328b9aaa8bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data available'])[3]/following::span[7]</value>
      <webElementGuid>fe2cdb33-618d-4afc-baa8-1e7c81dbca08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Percentage Process Transaction'])[3]/following::span[7]</value>
      <webElementGuid>1f1cb3c5-1489-4e93-8c10-2cb51ed3c942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb'])[1]/preceding::span[1]</value>
      <webElementGuid>101d58f8-a85f-43bd-9daf-c9d478cf8f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar'])[1]/preceding::span[2]</value>
      <webElementGuid>364399e1-d396-421d-bfb4-f45f26b98c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jan']/parent::*</value>
      <webElementGuid>3229e519-a672-498e-8b6f-a749abc91be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>6af385e5-0a51-40d5-b0cb-3b22327e82a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Jan' or . = 'Jan')]</value>
      <webElementGuid>5fc03857-9a08-4ecf-812a-cedec66d9839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
