<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_19</name>
   <tag></tag>
   <elementGuidId>ddc1d41f-de24-4deb-a110-b57100e795e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d65e1abb-46e2-401f-909f-8139cc06c469 > span.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='d65e1abb-46e2-401f-909f-8139cc06c469']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c82e72c7-e4dd-4988-9eef-31d816fb75af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ea098ff1-6029-49b2-8054-274952672096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link </value>
      <webElementGuid>1eacb60f-7629-407b-90e3-753fef85509e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e018997b-3da5-4797-8c55-667a458db633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2024/11/19</value>
      <webElementGuid>b984f7d1-5d31-4447-888b-7fb6277465e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Thursday, December 19, 2024</value>
      <webElementGuid>f8693895-e4d2-46cc-80ef-ff9e1d978967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>d982e608-4108-4572-b040-c227359ce049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d65e1abb-46e2-401f-909f-8139cc06c469&quot;)/span[@class=&quot;k-link&quot;]</value>
      <webElementGuid>23da09d8-3d54-4d6b-bc36-948905c356c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='d65e1abb-46e2-401f-909f-8139cc06c469']/span</value>
      <webElementGuid>4e00fe9e-5e52-4f25-848b-0f3c76032e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::span[19]</value>
      <webElementGuid>aa985f11-7df9-4115-9a7d-36fc730ea26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[2]/following::span[19]</value>
      <webElementGuid>0013af88-8500-4fcb-9cc9-ef4c7534135b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday, December 19, 2024'])[2]/preceding::span[24]</value>
      <webElementGuid>865cc195-0f54-46f2-9ea1-c05e6bab0bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[2]/table/tbody/tr[3]/td[5]/span</value>
      <webElementGuid>9f77f38b-7e43-4544-816b-2c7ccc61becc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Thursday, December 19, 2024' and (text() = '19' or . = '19')]</value>
      <webElementGuid>6c66b85c-2b3c-47b1-b64d-7e870cd27793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
