<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Rejected</name>
   <tag></tag>
   <elementGuidId>212fbb8d-75d9-42c2-99c9-bab5930fae8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Rejected:']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g:nth-of-type(6) > text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f64805af-92c0-4758-9750-eb48ca210b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>113.5951128941908</value>
      <webElementGuid>304437c0-8c07-4a7e-9cce-1f95b62e8f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>37.5</value>
      <webElementGuid>f20d8098-4635-4a64-ae67-b3b4cd534e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>f5ef2e2d-0879-4622-b5d1-0316c13d0417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgb(61, 61, 61)</value>
      <webElementGuid>4980e6cc-f988-4b2c-80cf-e8c2f7788b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>90efa607-2766-4af9-a60f-8120368f0680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rejected:</value>
      <webElementGuid>a4346b1b-5664-42bc-90af-51e2719d3f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrOutgoing&quot;)/svg[1]/g[1]/g[4]/g[1]/g[6]/text[1]</value>
      <webElementGuid>3945fc20-0d31-4bc1-9564-201ac1b47a62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rejected:']/parent::*</value>
      <webElementGuid>8c0818d0-f3af-4ee5-ba64-ad9452f7572c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = 'Rejected:' or . = 'Rejected:')]</value>
      <webElementGuid>ba39e5b5-5bed-4057-a9ea-2d381623444a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
