<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Draft</name>
   <tag></tag>
   <elementGuidId>0431eab5-8b5f-41df-a9c3-f80680b04195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Draft:']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g:nth-of-type(5) > text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf3e9084-2d9d-4159-b977-4f03ba6b6a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>121.6984456062873</value>
      <webElementGuid>78542b81-3e4b-453c-9b15-99d3b52e8a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>337.5</value>
      <webElementGuid>60831f73-fa24-4146-bba8-a050b6729643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ef52febe-4cc1-45fb-a93f-c17fae3810cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgb(61, 61, 61)</value>
      <webElementGuid>40910991-9c57-4f7e-910d-bd59cafb46b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>78d7815e-9dc8-4622-b147-5058642477c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft:</value>
      <webElementGuid>ca4d7d62-3767-4d03-8a7b-9f5b81226130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrOutgoing&quot;)/svg[1]/g[1]/g[4]/g[1]/g[5]/text[1]</value>
      <webElementGuid>3b675dd4-3c54-4ba1-b5a7-75bbae4d998f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Draft:']/parent::*</value>
      <webElementGuid>6dd0c6f3-7f91-41b3-bd53-091d9dd28489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = 'Draft:' or . = 'Draft:')]</value>
      <webElementGuid>085c34c6-c0e0-42b1-8707-24e02fa5cf17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
