<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_percnt_created</name>
   <tag></tag>
   <elementGuidId>60be307d-a3ee-48a0-99c3-5b498058e12d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='32.14% (18)']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>text:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfe32074-00a0-46a9-9771-0708a9879e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>413.02499739637574</value>
      <webElementGuid>f47aaac5-f4cf-484c-a577-9d6c45c3881c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>347.5</value>
      <webElementGuid>5cb4349d-abd2-4500-a3fb-c2761876d788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a7db566f-4dce-4533-b57a-2b4deafab757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgb(61, 61, 61)</value>
      <webElementGuid>73f4ceb1-5224-4406-a110-3b2730c6939f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e91567ed-ca9a-400f-9adf-385a6971a8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>32.14% (18)</value>
      <webElementGuid>7f6e2ab6-6bb3-4875-a237-a0c41d32b53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrOutgoing&quot;)/svg[1]/g[1]/g[4]/g[1]/g[4]/text[2]</value>
      <webElementGuid>b413ddd9-0d84-4e3c-acd9-06a327e0eabe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='32.14% (18)']/parent::*</value>
      <webElementGuid>12643c91-53fd-413e-8913-301009822897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = '32.14% (18)' or . = '32.14% (18)')]</value>
      <webElementGuid>03d889d3-679c-4ccd-98a6-3e745ccf6825</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
