<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Created</name>
   <tag></tag>
   <elementGuidId>4d17e74b-b156-43e8-99d8-325be0a4f407</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Created:']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g:nth-of-type(4) > text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64ede6e8-fabf-48c3-aa9a-96654bdbdb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>422.52499739637574</value>
      <webElementGuid>d7a4d1a1-f2bc-4c15-a2c2-ca47c5f69098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>333.5</value>
      <webElementGuid>1a5bc01a-a147-4bf9-9242-41b4673e583d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6dd77a89-0dab-4d3f-8779-785fc17e0453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgb(61, 61, 61)</value>
      <webElementGuid>4cf1e7ef-56d3-4ea2-aad2-1241d3a80f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>441757bd-844d-43ec-a074-06767e23e5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Created:</value>
      <webElementGuid>2ff3db81-5bcd-4f1c-832f-c200427cfd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrOutgoing&quot;)/svg[1]/g[1]/g[4]/g[1]/g[4]/text[1]</value>
      <webElementGuid>ed41ac6c-85c1-47c6-9957-e2b889e55140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Created:']/parent::*</value>
      <webElementGuid>43d7de69-be22-4f3d-9811-e6d148fea048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = 'Created:' or . = 'Created:')]</value>
      <webElementGuid>f1232123-e697-4c63-9a9b-ac04ca83cae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
