<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_CBFT</name>
   <tag></tag>
   <elementGuidId>740ffb37-72d4-4b6f-91ca-be88d8168c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabstrip-3 > div.card-content > div.d-grid.gap-2 > div.p-2 > div.row > div.col-12 > div.d-grid.gap-2 > div.p-2 > div.row > div.col.col-lg-3 > div.k-card > div.k-card-header > h3.k-card-title.text-uppercase.font-weight-bold.text-primary.text-uppercase.font-weight-bold.text-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabstrip-3']/div/div/div[2]/div/div/div/div/div/div/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>8f5a260b-57a3-4134-a88c-d0c442742781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-card-title text-uppercase font-weight-bold text-primary text-uppercase font-weight-bold text-primary</value>
      <webElementGuid>aa4ebccc-5c4f-4187-86ad-1cab891723e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CBFT</value>
      <webElementGuid>1a8a05a8-33f2-4e3f-973c-6c34bd014c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabstrip-3&quot;)/div[@class=&quot;card-content&quot;]/div[@class=&quot;d-grid gap-2&quot;]/div[@class=&quot;p-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;d-grid gap-2&quot;]/div[@class=&quot;p-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-lg-3&quot;]/div[@class=&quot;k-card&quot;]/div[@class=&quot;k-card-header&quot;]/h3[@class=&quot;k-card-title text-uppercase font-weight-bold text-primary text-uppercase font-weight-bold text-primary&quot;]</value>
      <webElementGuid>0c388c71-2b7a-42dc-9b49-b1b43c8efec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabstrip-3']/div/div/div[2]/div/div/div/div/div/div/div/div/h3</value>
      <webElementGuid>9024963b-a72f-41db-aa61-3b060ead3e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data available'])[2]/following::h3[1]</value>
      <webElementGuid>642a73f5-c996-4d17-9952-8ef9638c7d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[7]/preceding::h3[1]</value>
      <webElementGuid>9dc470f6-1ec4-47b5-a23e-5acb42eca809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posted'])[7]/preceding::h3[1]</value>
      <webElementGuid>ea705125-67d3-41cb-afce-ed57ae89f872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CBFT']/parent::*</value>
      <webElementGuid>bf4d35e9-dc1c-43f7-a2f6-7eb3dc3fc900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/div/div/div/div/div/h3</value>
      <webElementGuid>1f998fc7-5b86-4fdc-84c3-c1b0a6a636a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'CBFT' or . = 'CBFT')]</value>
      <webElementGuid>123d752e-570b-4f02-bc98-9ed9ac07224b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
