<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Anzo</name>
   <tag></tag>
   <elementGuidId>d964eb1a-8a0f-498e-bd32-32df1f8ac49c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabstrip-tab-3 > span.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tabstrip-tab-3']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3afd425-70f2-4421-923d-c9fed79de0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>05542a67-3db5-4890-b5fa-b7c271b9a9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>437ae68d-15ac-46c3-abfa-ece331a8238e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anzo</value>
      <webElementGuid>8bbc261b-eea7-4ce3-8046-00ab1aa7e614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabstrip-tab-3&quot;)/span[@class=&quot;k-link&quot;]</value>
      <webElementGuid>70ffcd9f-8da7-4fff-a790-e7c20392dae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tabstrip-tab-3']/span[2]</value>
      <webElementGuid>3c16f580-6190-4bbd-9062-db76178f843a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoming'])[2]/following::span[2]</value>
      <webElementGuid>a955a573-b5cb-4aee-b6a3-25f085df4256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outgoing'])[2]/following::span[4]</value>
      <webElementGuid>e232b259-d71c-4f3b-aa05-3e98a3bc6b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Transaction'])[1]/preceding::span[1]</value>
      <webElementGuid>9791ed83-ff95-49dc-abf0-d157a0a9dfb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anzo']/parent::*</value>
      <webElementGuid>b7943af9-dff5-4f11-a702-58a423f58c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span[2]</value>
      <webElementGuid>7f936096-d6f5-4dea-a99c-7ee32cec8801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Anzo' or . = 'Anzo')]</value>
      <webElementGuid>87967096-dcbc-4e54-b638-c2ce005b234f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
