<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Incoming</name>
   <tag></tag>
   <elementGuidId>5f10d56c-97e9-4897-85e1-3f5fa0b1a928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabstrip-tab-2 > span.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tabstrip-tab-2']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e163d8bf-6bda-4f3c-a6c3-c907b5899480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>f442c694-bc9c-46c1-8881-1db3bb536cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>95453576-141c-494e-8802-72ec3dc150ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Incoming</value>
      <webElementGuid>a906cd84-e962-4a1a-acfb-0c4826eb94d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabstrip-tab-2&quot;)/span[@class=&quot;k-link&quot;]</value>
      <webElementGuid>1cc808fe-2783-46c1-8dc5-1fd8bed367c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tabstrip-tab-2']/span[2]</value>
      <webElementGuid>098b27ff-f4ab-4930-b6f2-18f415743816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outgoing'])[2]/following::span[2]</value>
      <webElementGuid>9df9e927-d22f-4d77-bc66-ef34d1834407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DASHBOARD'])[1]/following::span[4]</value>
      <webElementGuid>fe4f031d-9d13-4b87-8116-ce6129e5957a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anzo'])[1]/preceding::span[2]</value>
      <webElementGuid>fde24cb2-d940-4c78-9cb3-26e2b1a3134e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span[2]</value>
      <webElementGuid>36c4635a-51bf-4be6-865c-0abb030efe6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Incoming' or . = 'Incoming')]</value>
      <webElementGuid>1df242bd-77e4-455b-9993-b43ad9622447</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
