<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Security</name>
   <tag></tag>
   <elementGuidId>68266f9a-b766-4625-9175-e07c0de59ae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.has-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c0a4aa3-6e78-4038-ba04-083c953e1b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-arrow</value>
      <webElementGuid>d84497ca-7e06-4b6f-82a2-c0e3e0ece9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void()</value>
      <webElementGuid>da2909b1-9e67-4eab-89fd-6a232925af7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>913a9cc0-e06b-4a64-bdb4-77a261a5db1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Security
                            </value>
      <webElementGuid>e9216971-7b41-4734-8e7c-935bc7213065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/li[@class=&quot;mega-menu mega-menu-sm&quot;]/a[@class=&quot;has-arrow&quot;]</value>
      <webElementGuid>d5344f8d-77ea-4a0e-aa15-defd893c2a72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu']/li[2]/a</value>
      <webElementGuid>e84ed97e-e882-4104-9bea-409a092e8faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>332bf77d-f596-4330-9a3a-4fd5d4fe3542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::a[1]</value>
      <webElementGuid>6d960683-1abb-4492-acf1-356c3e18f4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void()')]</value>
      <webElementGuid>4c594267-0a26-4045-962f-d6621da2399d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>e2ae5605-78d7-4bbd-82b0-d67c2dd42ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void()' and (text() = '
                                Security
                            ' or . = '
                                Security
                            ')]</value>
      <webElementGuid>c8d90127-2efc-4d4f-9888-daba3309f079</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
