<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_view_user</name>
   <tag></tag>
   <elementGuidId>77546aee-8326-477f-ba89-798d4e1321c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomView</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CustomView']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44222af0-bb46-4e81-9fa8-f6ef2be04bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomView</value>
      <webElementGuid>2fc44671-affe-468e-8bf8-6633e1c09d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>createKendoWindow(&quot;/user/userdetail?pId=2189&amp;pViewType=View&quot;);return false;</value>
      <webElementGuid>95b3698d-9823-4984-8af7-b2101bdac0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-magnify</value>
      <webElementGuid>9deacc2b-dfd9-40cf-b0e4-376512cbd7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd852bf7-8b17-4ca9-b97c-40daf635d055&quot;)/tr[@class=&quot;k-table-row k-master-row&quot;]/td[@class=&quot;k-table-td&quot;]/div[1]/a[@id=&quot;CustomView&quot;]</value>
      <webElementGuid>cacbdd8b-e520-4b14-a58a-58c8721486e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CustomView']</value>
      <webElementGuid>a8d1d2c5-bb88-420b-8fcd-3df034672087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='dd852bf7-8b17-4ca9-b97c-40daf635d055']/tr/td[2]/div/a[3]</value>
      <webElementGuid>8fcb2ba6-4965-4b49-889b-738c8863e99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>4b572841-6003-4326-b2f4-c102fcb43642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'CustomView']</value>
      <webElementGuid>c77f9bce-dc4e-48b7-b254-115f09e66d2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
