<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_delete_user</name>
   <tag></tag>
   <elementGuidId>1e4c5773-c6f7-43c6-b61e-ecc2643ba7ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomDelete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CustomDelete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f4cbd4c-8d37-4a94-99f4-95bfdb242c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomDelete</value>
      <webElementGuid>d37a11f0-409b-46e8-8f42-9a7e44064e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-delete</value>
      <webElementGuid>f7dd6709-37b7-4cb1-afcc-34464fda8a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>deleteRow(this)</value>
      <webElementGuid>ac093c2f-1818-4783-ac4b-6614a0005676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  </value>
      <webElementGuid>37f6df14-e58d-42c6-9734-70cfad7198e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c343d1c2-ef23-4bbf-a93d-3e6e299df73c&quot;)/tr[@class=&quot;k-table-row k-master-row&quot;]/td[@class=&quot;k-table-td&quot;]/div[1]/a[@id=&quot;CustomDelete&quot;]</value>
      <webElementGuid>1f988ae0-ce5d-45dc-9b16-4894559fcf57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CustomDelete']</value>
      <webElementGuid>6492854f-64cf-4fc4-b895-37753810c552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='c343d1c2-ef23-4bbf-a93d-3e6e299df73c']/tr/td[2]/div/a[2]</value>
      <webElementGuid>decfdc7c-3656-429f-a88b-fb709248dbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Access'])[1]/following::a[2]</value>
      <webElementGuid>0e4eef4f-9b61-47c4-8181-50f398f66a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member of'])[1]/following::a[2]</value>
      <webElementGuid>83cce397-ace4-45fc-8a3b-05d08eff3d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST ALI PROFES'])[1]/preceding::a[2]</value>
      <webElementGuid>f5bc7b65-3c60-48f5-95cc-bc926e87d6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALI TEST'])[1]/preceding::a[2]</value>
      <webElementGuid>c5e9ef59-105e-4e8b-aeca-f18b75606f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>ce458b34-423d-4a1e-ab3e-f947adea36a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'CustomDelete' and (text() = '  ' or . = '  ')]</value>
      <webElementGuid>ed03462c-d7f7-4abe-9672-de1ff4359434</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
