<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ADMINISTRATOR_Add</name>
   <tag></tag>
   <elementGuidId>e46e0b60-a296-4def-9b71-6946dc6c0c11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAddGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnAddGroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1a7b883-a73d-45c5-852b-de972c6a3291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>7ca719ed-2802-4d06-af8b-20167a913bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddGroup</value>
      <webElementGuid>cce5fd84-fe91-46de-bb37-c37ee1f0da3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mr-2</value>
      <webElementGuid>ae9ebf2c-a7f0-4ca8-9e5e-067f6e407389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddGroup&quot;)</value>
      <webElementGuid>1dcee22a-cee7-4971-a9aa-adf231499c7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnAddGroup']</value>
      <webElementGuid>1bd35d17-f92f-422b-a9a6-008bfadf4bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmUserInput']/div[5]/div/div/div[2]/button</value>
      <webElementGuid>edb6ae09-b7de-4b4e-8d1d-8056bb43ae6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMINISTRATOR'])[2]/following::button[1]</value>
      <webElementGuid>ab39f773-eab1-4c79-a6b6-98cf6dc9b53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[2]/following::button[1]</value>
      <webElementGuid>3630f9bc-837b-4a62-84fa-b9304fbb6d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/preceding::button[1]</value>
      <webElementGuid>f863ca86-a963-4e27-8bdb-c93e85c161bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Name'])[1]/preceding::button[1]</value>
      <webElementGuid>99f62507-f033-4358-a01c-6666da5b1571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>341a7efe-8352-4caa-9ad8-32f3f2374006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'Add' and @id = 'btnAddGroup']</value>
      <webElementGuid>9bfdead3-fa95-4374-bfd2-96ccb5c3053e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
