<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_edit_user</name>
   <tag></tag>
   <elementGuidId>612d23b2-c731-4b27-ba6c-983fd6ed0439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomEdit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CustomEdit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb8fb0b1-aa67-4788-b71b-85a35e0ad94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomEdit</value>
      <webElementGuid>42c80bdd-ffeb-44a9-9972-1380b3726185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>createKendoWindow(&quot;/user/userdetail?pId=2189&amp;pViewType=Edit&quot;);return false; </value>
      <webElementGuid>a15dbcdb-5975-4664-b9f6-2535b6743331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-lead-pencil</value>
      <webElementGuid>b736eaa7-3593-4200-a5fe-141bc2118f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd852bf7-8b17-4ca9-b97c-40daf635d055&quot;)/tr[@class=&quot;k-table-row k-master-row&quot;]/td[@class=&quot;k-table-td&quot;]/div[1]/a[@id=&quot;CustomEdit&quot;]</value>
      <webElementGuid>02565105-0370-4c89-8cf8-a0405980ce06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CustomEdit']</value>
      <webElementGuid>489c5cfb-12bd-48b3-a02b-7ef0e815725a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='dd852bf7-8b17-4ca9-b97c-40daf635d055']/tr/td[2]/div/a</value>
      <webElementGuid>2e7954ef-e391-433d-b711-839fdb4e49c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/a</value>
      <webElementGuid>a08fec0e-4dca-4d27-8f2e-c7d12c2038d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'CustomEdit']</value>
      <webElementGuid>06e5c912-afa2-46ad-8a71-0cbe23e99e65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
