<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_abasri_nav-header</name>
   <tag></tag>
   <elementGuidId>fa35fb61-38c3-4df8-be29-842100d95fd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.nav-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-wrapper']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>836845a9-6e6a-41d5-9b6c-23b207c7d053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-header</value>
      <webElementGuid>63fdd2d7-6f33-4188-ad03-fb45d8be6e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;nav-header&quot;]</value>
      <webElementGuid>25851296-48e5-47b0-8b73-d4dbe8e366ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div</value>
      <webElementGuid>6a8340a5-7d7c-4432-84d1-a1515c4748d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='abasri'])[1]/preceding::div[9]</value>
      <webElementGuid>81e95ea4-67ce-4329-b984-43f83e205413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMINISTRATOR | SYSTEM'])[1]/preceding::div[9]</value>
      <webElementGuid>35ae1b8e-ad8a-4a35-89d2-417a7e97a818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>33e6ee4a-1157-4e44-8f6e-63202499ab57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
