<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is Active_IsActive</name>
   <tag></tag>
   <elementGuidId>5a068048-6b6e-4a7f-ab0e-e30545db3c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbIsActive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbIsActive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7a88d02-a633-4a97-9269-c1ca5f0e5052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-checked</value>
      <webElementGuid>88feded5-9cbc-4063-9827-8f7a5ce42c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3217fe4-0d94-481f-8faa-3822c4e9131e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The IsActive field is required.</value>
      <webElementGuid>d3949f1f-a297-4623-a1d7-52fe80af7bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbIsActive</value>
      <webElementGuid>e20161e1-8c21-4f50-86a0-15f854adcb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsActive</value>
      <webElementGuid>9aa1612f-65f8-42a9-9a2c-dedcbbc4a891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>55c31807-2071-430a-8fe7-a5726ed9462f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f45088d-39d6-4c92-9e50-25dd468a64f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbIsActive&quot;)</value>
      <webElementGuid>fd3e76b0-fed4-47ae-bbf9-e28823f5006b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbIsActive']</value>
      <webElementGuid>f1b9402d-605e-4448-b0b7-9a0e6621db78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmUserInput']/div[4]/div/div/div/input</value>
      <webElementGuid>b341c994-972a-4e55-85ca-f1ea59dc752e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>42c9bd16-ce29-4027-9354-0745e2cc5c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cbIsActive' and @name = 'IsActive' and @type = 'checkbox']</value>
      <webElementGuid>958325d7-acd1-4bc9-84ce-305703b86adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
