<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DepartmentName</name>
   <tag></tag>
   <elementGuidId>5e6a15ea-2ce9-4124-ae7d-bacb225f1518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDepartment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDepartment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f1f634b-eef0-45ec-b572-c5cad1e12200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm k-input-inner</value>
      <webElementGuid>7bcdf7bc-9fdb-4876-b326-975388af85c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDepartment</value>
      <webElementGuid>c13539d6-3c83-43c8-b93c-4100b2437d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DepartmentName</value>
      <webElementGuid>af756759-4640-448f-8d8f-178697fe8d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e92975dc-fc20-4a48-b5a7-c7950b6bea0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>9983ca99-392a-474e-8bda-5321d90ad546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>85dae0de-a5d1-4810-a47a-3fa690ab4033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0e6528f1-5220-43f4-9ce9-54063f3b0cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDepartment&quot;)</value>
      <webElementGuid>73fcecff-1f79-43d7-9aba-0f4b48a77989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDepartment']</value>
      <webElementGuid>fe9ef85c-3976-4fa0-b919-15b951915745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmUserInput']/div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>695c18ed-6c91-4bb0-8051-43fca9af5b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>91ea11d2-2abf-46a9-b637-2579f1783fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtDepartment' and @name = 'DepartmentName' and @type = 'text']</value>
      <webElementGuid>a87dd696-a34b-42e7-83ae-dab2af0793bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
