<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_0309 - ANZ BALIKPAPAN BRANCH</name>
   <tag></tag>
   <elementGuidId>2eae2ba9-bd6f-4d89-9ffc-42948780260c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-list-item.k-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ddlBranch_listbox']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3492aa8f-af89-4f14-bf47-026b275a0dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8cf9c66f-0778-4fb9-b319-92e3cb3bcdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d36279a2-e06b-48f7-b319-4232d2a7c31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1ed5cb2d-faae-4bf3-b256-7e2674f4dac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item k-hover</value>
      <webElementGuid>14d1b91e-2ba9-4757-96ed-1f2d83bd3a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8dfb1500-7cf7-4a82-887d-9e9921ed9dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99f12f11-da4f-4b4c-9d4d-95a584fdf9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0309 - ANZ BALIKPAPAN BRANCH</value>
      <webElementGuid>564add5d-2f6d-4aec-9fb6-30491bb35467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlBranch_listbox&quot;)/li[@class=&quot;k-list-item k-hover&quot;]</value>
      <webElementGuid>cb46f807-9f06-4764-9cb7-8167d29bbc3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ddlBranch_listbox']/li</value>
      <webElementGuid>4059cf65-b96d-43ad-987f-1b550497ca5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- SELECT ONE --'])[5]/following::li[1]</value>
      <webElementGuid>65968893-8c68-4710-bf41-bf48b64708aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items to display'])[3]/following::li[1]</value>
      <webElementGuid>dcd3c402-23af-4068-9b66-5ce69c0f1872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[1]/preceding::li[29]</value>
      <webElementGuid>c2da8f05-1eb7-4776-bb86-ccf767979044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- SELECT ONE --'])[6]/preceding::li[29]</value>
      <webElementGuid>1dac8f63-94ab-4095-89aa-3bfae756648b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li</value>
      <webElementGuid>5faefbe1-9ae2-44f0-af2d-ce3ea65e9420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '0309 - ANZ BALIKPAPAN BRANCH' or . = '0309 - ANZ BALIKPAPAN BRANCH')]</value>
      <webElementGuid>30d0820e-bed1-4295-9382-affba1027f61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
