<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- ALL --                           _71b0bd</name>
   <tag></tag>
   <elementGuidId>21825d67-6afc-4716-b3b7-5e091d393cc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlIsActive']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ddlIsActive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fc0d5582-b451-43c7-899d-0d170160cc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlIsActive</value>
      <webElementGuid>67e60a0d-7822-43a2-bc40-35b7aba263b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlIsActive</value>
      <webElementGuid>166481e3-1fd2-4d50-94fb-9d1d09a04ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d5c72fa9-4fb1-48fb-ae9d-c2739557d167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    -- ALL --
                                                    Yes
                                                    No
                                                </value>
      <webElementGuid>3b1661b8-70b6-4e8c-b84e-aaa852dd6f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlIsActive&quot;)</value>
      <webElementGuid>a3d26d0c-8643-457c-8ded-80a0d1716819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlIsActive']</value>
      <webElementGuid>75f0e1ae-73b3-4ff0-928d-3ea3968faac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseTwo']/div/div/div[2]/div/div/select</value>
      <webElementGuid>3f362808-0aae-48bd-9bd4-f4e0b5808b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Active'])[1]/following::select[1]</value>
      <webElementGuid>fa20e3f5-c589-40b6-bae9-06b3dc4731f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyword'])[1]/following::select[1]</value>
      <webElementGuid>c7e89e60-8f38-49d8-8ded-2cd779649745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4d7f7b0c-cbd1-4f91-8639-9e808a29c414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ddlIsActive' and @name = 'ddlIsActive' and (text() = '
                                                    -- ALL --
                                                    Yes
                                                    No
                                                ' or . = '
                                                    -- ALL --
                                                    Yes
                                                    No
                                                ')]</value>
      <webElementGuid>19e4f918-65b3-46db-ad0b-62b1a6a8e8e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
