<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- ALL --                                                    Yes                                                    No</name>
   <tag></tag>
   <elementGuidId>18268b35-a27a-4ef2-901e-a75726e9a16a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ddlIsActive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlIsActive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>67b95fb4-a2a7-452e-a565-1086edac2f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlIsActive</value>
      <webElementGuid>5ad4adf7-e0b6-4b45-899b-3e283c5b95e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlIsActive</value>
      <webElementGuid>90633121-877c-457e-b062-0f2d21509857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3bad3914-0e6d-4c3b-8c1a-aefd23511b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    -- ALL --
                                                    Yes
                                                    No
                                                </value>
      <webElementGuid>1dd7abeb-424f-4748-9ae5-fe8e54286e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlIsActive&quot;)</value>
      <webElementGuid>ad9d5e18-b8d6-44a5-91a7-6de85da1ccb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlIsActive']</value>
      <webElementGuid>8a6d40a9-b99a-4f34-a2aa-458e4434660d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseTwo']/div/div/div[2]/div/div/select</value>
      <webElementGuid>bf06fc1a-0783-45f4-84d2-a08ba30a5203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Active'])[1]/following::select[1]</value>
      <webElementGuid>b746e2d3-7734-4c30-b5ce-4dbfcedb874c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyword'])[1]/following::select[1]</value>
      <webElementGuid>cc882495-4d73-4b35-8723-eeb4472a00a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6abba471-eeb9-4d69-bf67-37e8e0b7583f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ddlIsActive' and @name = 'ddlIsActive' and (text() = '
                                                    -- ALL --
                                                    Yes
                                                    No
                                                ' or . = '
                                                    -- ALL --
                                                    Yes
                                                    No
                                                ')]</value>
      <webElementGuid>f637d581-b5fd-4cb7-af31-4b4b4f968d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
