<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_User Name</name>
   <tag></tag>
   <elementGuidId>cdbcf2ca-02da-4d30-b9d0-c2f67f94b3ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e442e0cb-dc31-4fda-a171-e6970ab75d64 > span.k-cell-inner > span.k-link > span.k-column-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='e442e0cb-dc31-4fda-a171-e6970ab75d64']/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2f3bdff1-5c25-49c7-ab80-0cae6d0ac4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-column-title</value>
      <webElementGuid>001efdfa-23b5-42f0-a184-dcf0b61b9cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>f066b78e-2459-4e3d-9c60-fc1bd6443680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e442e0cb-dc31-4fda-a171-e6970ab75d64&quot;)/span[@class=&quot;k-cell-inner&quot;]/span[@class=&quot;k-link&quot;]/span[@class=&quot;k-column-title&quot;]</value>
      <webElementGuid>f9701c1c-b63b-4112-8e8a-122467773437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='e442e0cb-dc31-4fda-a171-e6970ab75d64']/span/span/span</value>
      <webElementGuid>f3bbc4f8-0086-4c65-9408-64ab6a85cb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Name'])[1]/following::span[3]</value>
      <webElementGuid>724dee97-16a3-4787-8e89-5cbf33424039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Id'])[1]/following::span[6]</value>
      <webElementGuid>f88daaae-ebb7-4437-b647-3e3d1af5f0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/preceding::span[1]</value>
      <webElementGuid>1bcf017d-99d7-4671-a4c5-6077c750d481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::span[4]</value>
      <webElementGuid>8d0b96c5-5a4a-4ad4-a7d8-9da13722fe7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Name']/parent::*</value>
      <webElementGuid>f45d39c1-e867-4431-b2d3-1dc896ccf123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/span/span/span</value>
      <webElementGuid>c24a1013-e134-4ed1-8177-8249f002d408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'User Name' or . = 'User Name')]</value>
      <webElementGuid>d84d7f5a-dbc8-4ccd-a90c-6c4f0ac4934f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
