<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- SELECT ONE --Branch Code</name>
   <tag></tag>
   <elementGuidId>a33aca85-3c22-41a8-a60e-405c63edafec</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[3]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '-- SELECT ONE --' or . = '-- SELECT ONE --')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-input-value-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>877d4fe5-b737-4c48-934d-647ec4ffaa93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-value-text</value>
      <webElementGuid>81bf59fe-9cf6-49ed-8986-f3f3b94a4874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- SELECT ONE --</value>
      <webElementGuid>fd508457-2edf-4f85-aa51-82b76d96921e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a761bf73-1c01-4bb5-8cc0-05613974e34e&quot;)/span[@class=&quot;k-input-value-text&quot;]</value>
      <webElementGuid>3d1b7bdf-2136-427d-9f9a-1df42dd3bdf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a761bf73-1c01-4bb5-8cc0-05613974e34e']/span</value>
      <webElementGuid>55e5d04f-7f6a-40af-b9ca-ffc83bac2359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[3]</value>
      <webElementGuid>2847efc4-85fc-4e00-ac2f-b2c1abe19293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::span[3]</value>
      <webElementGuid>b2c676ac-8e29-4dea-92d7-d82ce57c629d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-- SELECT ONE --']/parent::*</value>
      <webElementGuid>2da6cd9d-98ee-4a1a-90d4-7ae2344cb085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/span/span/span</value>
      <webElementGuid>15efc253-4970-49d2-ac94-9a61ea4d2261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '-- SELECT ONE --' or . = '-- SELECT ONE --')]</value>
      <webElementGuid>88ca908d-e810-4587-a4fc-6a078f154739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
