<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_0309 - ANZ BALIKPAPAN BRANCH</name>
   <tag></tag>
   <elementGuidId>678d6e22-b9a7-4351-ade1-a3da1b4f1f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-list-item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ddlBranch_listbox']/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>77eb462a-09ba-4f21-a20a-208011110c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item-text</value>
      <webElementGuid>3df48595-246a-4094-9bd6-d55b35dae902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0309 - ANZ BALIKPAPAN BRANCH</value>
      <webElementGuid>a0f7a63b-68bb-421f-9230-62a2db84364d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlBranch_listbox&quot;)/li[@class=&quot;k-list-item k-hover&quot;]/span[@class=&quot;k-list-item-text&quot;]</value>
      <webElementGuid>f339f05b-fe31-44d3-95c8-98bb8e349475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ddlBranch_listbox']/li/span</value>
      <webElementGuid>06e01135-4c71-4ec2-b7f4-ad2903ac5cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- SELECT ONE --'])[5]/following::span[1]</value>
      <webElementGuid>050644e3-22dc-480e-94ea-5a753479faac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items to display'])[3]/following::span[1]</value>
      <webElementGuid>5ad98f51-5f79-4076-a64b-4cb08d780420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[1]/preceding::span[29]</value>
      <webElementGuid>1d67b04c-7e0c-4223-a3a3-e6e4776e777a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- SELECT ONE --'])[6]/preceding::span[29]</value>
      <webElementGuid>23c1336e-2b65-427e-84da-d546baba2371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0309 - ANZ BALIKPAPAN BRANCH']/parent::*</value>
      <webElementGuid>9c449528-a47a-4c70-a6a6-dee4a501a81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>02070109-fd9b-4a58-ba28-dc465ba4eb7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '0309 - ANZ BALIKPAPAN BRANCH' or . = '0309 - ANZ BALIKPAPAN BRANCH')]</value>
      <webElementGuid>cb5f2e23-5451-48f1-ba9e-129fec071a3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
