<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Title</name>
   <tag></tag>
   <elementGuidId>f4285b25-9fb4-4d0d-af99-be58a5ab080b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b09fc661-e158-4c76-ace6-d1aff00d06a9 > span.k-cell-inner > span.k-link > span.k-column-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='b09fc661-e158-4c76-ace6-d1aff00d06a9']/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a4a379b-be28-4afa-b4a8-ae264e4c3ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-column-title</value>
      <webElementGuid>d3a2ac2b-5e90-488a-b8a9-17c729bb6748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>2acb81bf-03b5-442f-aac7-e392dd99db34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b09fc661-e158-4c76-ace6-d1aff00d06a9&quot;)/span[@class=&quot;k-cell-inner&quot;]/span[@class=&quot;k-link&quot;]/span[@class=&quot;k-column-title&quot;]</value>
      <webElementGuid>8970f4e8-e82a-49c1-960e-cff15824f263</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='b09fc661-e158-4c76-ace6-d1aff00d06a9']/span/span/span</value>
      <webElementGuid>9b074aae-d9ee-413c-82e2-49bf48442ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name'])[1]/following::span[3]</value>
      <webElementGuid>0bb3fc4d-8de7-4f16-84d6-80bdd2b27e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Name'])[1]/following::span[6]</value>
      <webElementGuid>2af8a034-1a88-4b01-a357-d38813fbe06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::span[1]</value>
      <webElementGuid>e765792d-89c3-494f-8eb8-ff1895976684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch Name'])[1]/preceding::span[4]</value>
      <webElementGuid>a16052b5-80ee-41ac-b09f-f06d0dd23cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Title']/parent::*</value>
      <webElementGuid>6d6cbfce-93a0-48c7-ba5d-4c5533d5a52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/span/span/span</value>
      <webElementGuid>857a12d4-d738-4e31-9c9a-ded9673222af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Title' or . = 'Title')]</value>
      <webElementGuid>2a067519-5740-4dd4-b522-960e332f2f99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
