<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Last Access</name>
   <tag></tag>
   <elementGuidId>107ea3b8-99fa-48ed-8013-be596d553564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c4b0aab3-b9cb-44fe-9a7f-b68ac01f6318 > span.k-cell-inner > span.k-link > span.k-column-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b1beccf-5a24-49ef-b36e-aaf273050227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-column-title</value>
      <webElementGuid>e7ebc85d-a4b0-48ed-b1f4-cc9651bc8cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last Access</value>
      <webElementGuid>c5a53b8e-26f2-4e90-8cd3-d8ec7b22740b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c4b0aab3-b9cb-44fe-9a7f-b68ac01f6318&quot;)/span[@class=&quot;k-cell-inner&quot;]/span[@class=&quot;k-link&quot;]/span[@class=&quot;k-column-title&quot;]</value>
      <webElementGuid>cef873f8-a1a7-4670-b626-f6477378de77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='c4b0aab3-b9cb-44fe-9a7f-b68ac01f6318']/span/span/span</value>
      <webElementGuid>fc4df531-3064-42d4-9c38-57a3d4bf1225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member of'])[1]/following::span[3]</value>
      <webElementGuid>0407c2ce-ba3a-4f11-9ed7-bc10e2f5e021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deparment Name'])[1]/following::span[6]</value>
      <webElementGuid>afca9cf9-ed8f-46ef-afde-da525c25c8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER DUA CHECKER'])[1]/preceding::span[1]</value>
      <webElementGuid>0365358c-ace5-49a4-8cb3-1e5f519d0a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER2'])[1]/preceding::span[1]</value>
      <webElementGuid>cdc33930-e373-4ff4-8cb8-416885577f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Last Access']/parent::*</value>
      <webElementGuid>af874071-041c-4195-9271-0328f3780702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[11]/span/span/span</value>
      <webElementGuid>803deff3-ac0e-4d72-8d6c-53c89aa97757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Last Access' or . = 'Last Access')]</value>
      <webElementGuid>0fe3c266-cd31-4654-826a-bd4d155b160f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
