<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Status</name>
   <tag></tag>
   <elementGuidId>6c06151f-2f93-475b-a892-fbf160e79c58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f17aae45-8a60-4030-9f9b-fd14f864018e > span.k-cell-inner > span.k-link > span.k-column-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='f17aae45-8a60-4030-9f9b-fd14f864018e']/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>679a84fa-b687-4dab-ae51-8927745e48a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-column-title</value>
      <webElementGuid>91cbb5fb-63b3-4617-8992-24e4253eac60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>86f75dfa-cecc-417c-9c2b-d953b46c6117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f17aae45-8a60-4030-9f9b-fd14f864018e&quot;)/span[@class=&quot;k-cell-inner&quot;]/span[@class=&quot;k-link&quot;]/span[@class=&quot;k-column-title&quot;]</value>
      <webElementGuid>56435108-20dc-4e0e-855a-cc11062a2aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='f17aae45-8a60-4030-9f9b-fd14f864018e']/span/span/span</value>
      <webElementGuid>0d31e961-9ab0-482c-8304-a6370f00764f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::span[3]</value>
      <webElementGuid>2db9e983-9d01-432d-b351-2eda4841a878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name'])[1]/following::span[6]</value>
      <webElementGuid>d17e63ea-0151-4b40-a876-af3208a28604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch Name'])[1]/preceding::span[1]</value>
      <webElementGuid>4883fca5-3ace-4765-9e50-025c548586ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deparment Name'])[1]/preceding::span[4]</value>
      <webElementGuid>dc29d849-b5e1-4597-b711-ccea1607a4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Status']/parent::*</value>
      <webElementGuid>1c1bc5fa-49b4-4531-b7a7-f0bac44f28e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/span/span/span</value>
      <webElementGuid>c7e2ff65-11f1-4e6a-9c70-616f03f7f28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Status' or . = 'Status')]</value>
      <webElementGuid>a5954308-35c0-480d-9cea-d4041bf447ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
