<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_0320 - ANZ CBD PLUIT BRANCH</name>
   <tag></tag>
   <elementGuidId>a73da376-9c17-4653-a163-ba9e794b63ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ddlBranch_listbox']/li[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5737b51-8df2-44d5-b328-1a1dfefdcfb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-list-item-text</value>
      <webElementGuid>85a04690-7249-4afe-a8d7-1a7e7ecec123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0320 - ANZ CBD PLUIT BRANCH</value>
      <webElementGuid>eb7a8dbd-56df-4eaf-a49b-10663174dc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlBranch_listbox&quot;)/li[@class=&quot;k-list-item&quot;]/span[@class=&quot;k-list-item-text&quot;]</value>
      <webElementGuid>4704727f-97af-428f-9f82-4a8ada4e6423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ddlBranch_listbox']/li[3]/span</value>
      <webElementGuid>1b278d0e-9bee-40d6-9dcd-ea505e2e6146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- SELECT ONE --'])[4]/following::span[3]</value>
      <webElementGuid>6da06c85-c761-4179-b2aa-118f9cf6fa9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BKT'])[1]/following::span[9]</value>
      <webElementGuid>ff84e7ef-8024-40bd-b202-d5049a2cd87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[1]/preceding::span[27]</value>
      <webElementGuid>f1db8f1f-5c8c-4c7a-9012-1c7e5909ccf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- SELECT ONE --'])[5]/preceding::span[27]</value>
      <webElementGuid>bac37ec8-74f7-47fe-840f-3cf2b9ab0eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0320 - ANZ CBD PLUIT BRANCH']/parent::*</value>
      <webElementGuid>a86cc949-55b0-4dd1-83ae-f7d8d3890063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>5bc7306f-c4d8-4e68-9ab1-436836873f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '0320 - ANZ CBD PLUIT BRANCH' or . = '0320 - ANZ CBD PLUIT BRANCH')]</value>
      <webElementGuid>6547ca1c-3107-4327-b7e0-5cda8868eace</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
