<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_CBFT</name>
   <tag></tag>
   <elementGuidId>582cd3cf-3844-49a4-97ed-a8b949806fb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='BKT'])[1]/following::td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>21b7b9ae-7c7c-4fd4-baf5-8ad070a04405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-table-td</value>
      <webElementGuid>3919abc3-09e7-4c7e-9cbd-54c9094053ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>89e902ef-f4bf-4df2-b5e2-64eb0745eba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CBFT</value>
      <webElementGuid>a8c34dcf-c45e-4f74-bb04-4890cf29890e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;de87ea60-b369-4df3-bdad-f352465dcc51&quot;)/tr[@class=&quot;k-alt k-table-row k-table-alt-row k-master-row&quot;]/td[@class=&quot;k-table-td&quot;]</value>
      <webElementGuid>f8c5d8c1-47c2-48c8-8a58-08fc92ba7df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='de87ea60-b369-4df3-bdad-f352465dcc51']/tr[2]/td[2]</value>
      <webElementGuid>c490392e-7d77-45ad-a545-fc2da4955351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BKT'])[1]/following::td[2]</value>
      <webElementGuid>1d0bd767-498c-41fb-8195-1c6ab1a0d8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Name'])[1]/following::td[4]</value>
      <webElementGuid>4fb11fc1-4e0c-4f74-8e6b-375dd791a699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- SELECT ONE --'])[1]/preceding::td[1]</value>
      <webElementGuid>bef591c5-df7b-406c-9dbe-5f2b4395f0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[1]/preceding::td[1]</value>
      <webElementGuid>45f9e086-b838-4629-8a6a-4fd538ad162e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/div/div[2]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>885558fa-977b-4059-acba-5aba3ae7cf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'CBFT' or . = 'CBFT')]</value>
      <webElementGuid>dd0c7248-571a-4559-8ad5-4180f34f39ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
