<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_TestQA1</name>
   <tag></tag>
   <elementGuidId>3af57234-4f51-4cfa-b045-f90b2c87d54d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Name'])[1]/following::td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8459d245-1965-487f-9f40-d0b6a6d91007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-table-td</value>
      <webElementGuid>7260a668-4e42-42ff-939b-2f75c8aee0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>94f29dd8-cdf5-4c12-99ca-6dfb641b0dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TestQA1</value>
      <webElementGuid>0db8c516-b46f-461b-a46c-60b042add5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b36f017e-6e94-4553-936a-c1bad704a1ca&quot;)/tr[@class=&quot;k-alt k-table-row k-table-alt-row k-master-row&quot;]/td[@class=&quot;k-table-td&quot;]</value>
      <webElementGuid>5ad24896-e629-41b2-91b3-9a6c02f67ad6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='b36f017e-6e94-4553-936a-c1bad704a1ca']/tr[2]/td[2]</value>
      <webElementGuid>23f6bbd6-778d-443d-8438-7c2014f6aaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMINISTRATOR'])[3]/following::td[2]</value>
      <webElementGuid>d7f91245-cdab-4324-8884-db1fc38e7049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Name'])[1]/following::td[4]</value>
      <webElementGuid>f064b06e-b9f0-4741-b888-f868f778c96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Addtional Branch'])[1]/preceding::td[1]</value>
      <webElementGuid>6384e521-ecf6-4c8d-8a27-24ccef5d12ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- SELECT ONE --'])[1]/preceding::td[1]</value>
      <webElementGuid>560636bc-6651-4fe6-b91b-7fa8cac4cb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>e9e90ea7-68d2-451c-b474-74f11a20a902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'TestQA1' or . = 'TestQA1')]</value>
      <webElementGuid>3ef23903-0bf6-4b09-bafd-adbd60ed4ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
