<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>view_BKT_btnClose</name>
   <tag></tag>
   <elementGuidId>033c0ffe-1153-40ce-a016-446a1af28474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnClose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnClose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64bbdd85-d01f-4cfb-bbbd-bd6d949d0484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c35a5dd3-d8f7-4303-991f-381fdf8d77e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnClose</value>
      <webElementGuid>13994018-9ddb-405e-ab63-f596893d6a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>793e8457-f13b-4977-8172-abf0dc38ab27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnClose</value>
      <webElementGuid>2a7db7f5-d1dc-4ba7-a32a-5951e99bfaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-dark</value>
      <webElementGuid>cb606547-b516-4b16-84f8-1222bdafff2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnClose&quot;)</value>
      <webElementGuid>9110e15c-d5e2-431e-aa9e-1676ea5ced60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnClose']</value>
      <webElementGuid>e295a0b7-4d4a-4194-b381-3674974251ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmUserInput']/div[8]/input</value>
      <webElementGuid>93cf3472-a4dd-41ed-bee0-92d2c7af1e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>445e48ba-6df1-413a-be56-60968a4b0f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnClose' and @id = 'btnClose']</value>
      <webElementGuid>f6b66eee-a255-44ce-88cd-da775513c68c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
